import React from 'react';
import './main.css';
import checkIcon from './check.gif';

const App = (): JSX.Element => (
  <div>
    <div className="text">
      Generated by yeoman react-eslint-airbnb-prettier and using typescript
    </div>
    <img src={checkIcon} alt="check icon" />
  </div>
);

export default App;
